name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: n=1
      id: n-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: n=1
        setup-command: make proj2
        command: "./proj2 1"
        input: ''
        expected-output: '1'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: n=5
      id: n-5
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: n=5
        setup-command: make proj2
        command: "./proj2 5"
        input: ''
        expected-output: |-
          17    24     1     8    15 
             23     5     7    14    16 
              4     6    13    20    22 
             10    12    19    21     3 
             11    18    25     2     9
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: n=15
      id: n-15
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: n=15
        setup-command: make proj2
        command: "./proj2 15"
        input: ''
        expected-output: |-
          122             139             156             173             190             207             224               1              18              35              52              69              86             103             120 
                      138             155             172             189             206             223              15              17              34              51              68              85             102             119             121 
                      154             171             188             205             222              14              16              33              50              67              84             101             118             135             137 
                      170             187             204             221              13              30              32              49              66              83             100             117             134             136             153 
                      186             203             220              12              29              31              48              65              82              99             116             133             150             152             169 
                      202             219              11              28              45              47              64              81              98             115             132             149             151             168             185 
                      218              10              27              44              46              63              80              97             114             131             148             165             167             184             201 
                        9              26              43              60              62              79              96             113             130             147             164             166             183             200             217 
                       25              42              59              61              78              95             112             129             146             163             180             182             199             216               8 
                       41              58              75              77              94             111             128             145             162             179             181             198             215               7              24 
                       57              74              76              93             110             127             144             161             178             195             197             214               6              23              40 
                       73              90              92             109             126             143             160             177             194             196             213               5              22              39              56 
                       89              91             108             125             142             159             176             193             210             212               4              21              38              55              72 
                      105             107             124             141             158             175             192             209             211               3              20              37              54              71              88 
                      106             123             140             157             174             191             208             225               2              19              36              53              70              87             104
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: n is even
      id: n-is-even
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: n is even
        setup-command: make proj2
        command: "./proj2 2"
        input: ''
        expected-output: 'Error: invalid number'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: n is negative
      id: n-is-negative
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: n is negative
        setup-command: make proj2
        command: "./proj2 -2"
        input: ''
        expected-output: 'Error: invalid number'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: n greater than 15
      id: n-greater-than-15
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: n-greater-than-15
        setup-command: make proj2
        command: "./proj2 16"
        input: ''
        expected-output: 'Error: invalid number'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        N-1_RESULTS: "${{steps.n-1.outputs.result}}"
        N-5_RESULTS: "${{steps.n-5.outputs.result}}"
        N-15_RESULTS: "${{steps.n-15.outputs.result}}"
        N-IS-EVEN_RESULTS: "${{steps.n-is-even.outputs.result}}"
        N-IS-NEGATIVE_RESULTS: "${{steps.n-is-negative.outputs.result}}"
        N-GREATER-THAN-15: "${{steps.n-greater-than-15.outputs.result}}"
      with:
        runners: n-1,n-5,n-15,n-is-even,n-is-negative,n-greater-than-15