name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: n=1
      id: n-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: n=1
        setup-command: make proj2
        command: "./proj2 1"
        input: ''
        expected-output: '1'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: n=5
      id: n-5
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: n=5
        setup-command: make proj2
        command: "./proj2 5"
        input: ''
        expected-output: |-
          17    24     1     8    15
             23     5     7    14    16
              4     6    13    20    22
             10    12    19    21     3
             11    18    25     2     9
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        N-1_RESULTS: "${{steps.n-1.outputs.result}}"
        N-5_RESULTS: "${{steps.n-5.outputs.result}}"
      with:
        runners: n-1,n-5
